FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libglew-dev libglfw3-dev cmake gcc libcurl4-gnutls-dev tesseract-ocr libtesseract-dev libleptonica-dev clang libclang-dev

COPY . /repo
WORKDIR /repo/linux
RUN ./build -without-rust

FROM ubuntu:20.04 as package
COPY --from=builder /repo/linux/ccextractor /repo/linux/ccextractor

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libtesseract-dev 